name: Spring Boot Test Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Run Unit Tests
      run: mvn clean test

    - name: Generate JaCoCo Report
      run: mvn jacoco:report

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: junit-test-results
        path: target/surefire-reports/

    - name: Upload JaCoCo Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: target/site/jacoco/

    # Optional: Upload code coverage to Codecov (requires secret)
    # - name: Upload to Codecov
    #   uses: codecov/codecov-action@v4
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     files: target/site/jacoco/jacoco.xml
    #     fail_ci_if_error: true
